// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmn1cvPkaJ6_jbvjsapXzBz5KO-SJ444U',
    appId: '1:417970120063:web:0d20fd133564243a6c664a',
    messagingSenderId: '417970120063',
    projectId: 'driver-3d757',
    authDomain: 'driver-3d757.firebaseapp.com',
    storageBucket: 'driver-3d757.appspot.com',
    measurementId: 'G-XQRZ41XTBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDomuhsaqTv4Gr5b9E4NmkwCM_4DWtl6u0',
    appId: '1:417970120063:android:54b262a662ae5ae06c664a',
    messagingSenderId: '417970120063',
    projectId: 'driver-3d757',
    storageBucket: 'driver-3d757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-p2MEDATJDZTYBUSAXNqSJ-yD4_b5qg',
    appId: '1:417970120063:ios:7dcaa94255ade96f6c664a',
    messagingSenderId: '417970120063',
    projectId: 'driver-3d757',
    storageBucket: 'driver-3d757.appspot.com',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-p2MEDATJDZTYBUSAXNqSJ-yD4_b5qg',
    appId: '1:417970120063:ios:7dcaa94255ade96f6c664a',
    messagingSenderId: '417970120063',
    projectId: 'driver-3d757',
    storageBucket: 'driver-3d757.appspot.com',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmn1cvPkaJ6_jbvjsapXzBz5KO-SJ444U',
    appId: '1:417970120063:web:5bfb77a3f8e255c06c664a',
    messagingSenderId: '417970120063',
    projectId: 'driver-3d757',
    authDomain: 'driver-3d757.firebaseapp.com',
    storageBucket: 'driver-3d757.appspot.com',
    measurementId: 'G-ZZP0NPTP3R',
  );
}
